services:
  postgres:
    image: postgres:latest
    container_name: postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: superheroes
    ports:
      - "5432:5432"
    networks:
      - app-network

  rabbitmq:
    image: rabbitmq:management
    container_name: rabbitmq
    restart: always
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    ports:
      - "5672:5672" # RabbitMQ communication
      - "15672:15672" # RabbitMQ web UI
    healthcheck:
      test: ["CMD", "rabbitmqctl", "status"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - app-network

  gateway-api:
    build: ./gateway-api
    container_name: gateway-api
    restart: always
    depends_on:
      postgres:
        condition: service_started
      rabbitmq:
        condition: service_healthy
    environment:
      DATABASE_URL: postgres://postgres:password@postgres:5432/superheroes
      RABBITMQ_URL: amqp://guest:guest@rabbitmq:5672
      SUPERHERO_RABBITMQ_QUEUE: superheroes
      TIMERS_RABBITMQ_QUEUE: timers
      PORT: 3000
    ports:
      - "3000:3000"
    networks:
      - app-network

  superhero-microservice:
    build: ./superhero-microservice
    container_name: superhero-microservice
    restart: always
    depends_on:
      postgres:
        condition: service_started
      rabbitmq:
        condition: service_healthy
    environment:
      DATABASE_URL: postgres://postgres:password@postgres:5432/superheroes
      RABBITMQ_URL: amqp://guest:guest@rabbitmq:5672
      RABBITMQ_QUEUE: superheroes
    networks:
      - app-network

  timer-microservice:
    build: ./timer-microservice
    container_name: timer-microservice
    restart: always
    depends_on:
      postgres:
        condition: service_started
      rabbitmq:
        condition: service_healthy
    environment:
      DATABASE_URL: postgres://postgres:password@postgres:5432/superheroes
      RABBITMQ_URL: amqp://guest:guest@rabbitmq:5672
      RABBITMQ_QUEUE: timers
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
